version: "3.9"
services:
  GivTCP:
    image: britkat/giv_tcp-dev:latest
    ports:
      - "1883:1883"                   # MQTT
      - "8098:8099"                   # REST and Config web server (https on 8098)
      - "3000:3000"                   # WEB Dashboard
    volumes:
      - c:\config\GivTCP:/config/GivTCP
    network_mode: "host"
    restart: always
    privileged: true
    environment:
      - TZ = "Europe/London"
